version: "3.9"
services:
  backend:
    image: hexalayer-backend:latest
    build:
      context: .
    container_name: hexalayer-backend-container
    ports:
      - "5002:5000"
      - "5001:5001"
      - "5003:5003"
    env_file:
      - .env
    restart: unless-stopped